# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghissue < Formula
  desc ""
  homepage "https://github.com/hcgatewood/homebrew-ghissue"
  version "0.1.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hcgatewood/ghissue/releases/download/v0.1.3/ghissue_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "65b6ac1e41bc500e8932dd5ac063fca194770b42aef2eb7e04b5e03f97a3faec"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hcgatewood/ghissue/releases/download/v0.1.3/ghissue_0.1.3_Linux_x86_64.tar.gz"
      sha256 "94efae9df6e443046763a31647f3541c4bdbb6598ef00419f229fa097e9a7f07"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hcgatewood/ghissue/releases/download/v0.1.3/ghissue_0.1.3_Linux_arm64.tar.gz"
      sha256 "47a81ff2b51ab3e3b6d246959ec6a5c16186eee13008a53fb83d45787b47c60e"
    end
  end

  def install
    bin.install "ghissue"
  end
end
