# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghissue < Formula
  desc ""
  homepage "https://github.com/hcgatewood/ghissue"
  version "0.1.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hcgatewood/ghissue/releases/download/v0.1.1/ghissue_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "90b0961c9dd1a1aeef312ae18500096443a31612c0fa99342eeb57a91918e268"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hcgatewood/ghissue/releases/download/v0.1.1/ghissue_0.1.1_Linux_x86_64.tar.gz"
      sha256 "18d1b5db58c9f93a4a08e3d2caccfe88533d2bc789f5d9bf66931d4df4aaa146"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hcgatewood/ghissue/releases/download/v0.1.1/ghissue_0.1.1_Linux_arm64.tar.gz"
      sha256 "843dbd7de3f5cf3c65d19f8d430d1c93041e19043b6171ac460905dfc25aafa9"
    end
  end

  def install
    bin.install "ghissue"
  end
end
